version: "2"
services:
  db:
    image: postgis/postgis:latest
    container_name: vn-api-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=orma
      - POSTGRES_USER=orma
      - POSTGRES_PASSWORD=orma
      - PGDATA=/var/lib/postgresql/data/pgdata

  redis:
    container_name: vn-redis
    image: redis
    ports:
      - "6379:6379"
    command: redis-server

  # api:
  #   build: .
  #   image: developmentseed/openroads-vn-api:latest
  #   env_file: .env
  #   depends_on:
  #     - db
  #     - redis
  #   ports:
  #     - "80:4000"
  #   environment:
  #     - DATABASE_URL=postgres://orma@db:5432/orma
  #     - REDIS_URL=redis://redis:6379
#
#   vn-tiler:
#     image: developmentseed/openroads-vn-tiler:latest
#     env_file: .env
#     command: ./cron.sh
#     environment:
#       - S3_TEMPLATE=s3://openroads-vn-tiles/tiles/{z}/{x}/{y}.vector.pbf
#       - S3_DUMP_BUCKET=openroads-vn-dumps
#       - DATABASE_URL=postgres://postgres@db:5432/openroads
#
#   tilemap:
#     image: developmentseed/openroads-tilemap:latest
#     env_file: .env
#     ports:
#       - "3000:3000"
#     environment:
#       - BUCKET_URL=http://openroads-vn-tiles.s3-website-us-east-1.amazonaws.com/tiles


#   deploy:
#     image: developmentseed/openroads-vn-api:latest
#     command: node_modules/.bin/kes cf update -k aws/app --env-file .env
#     env_file: .env
