
# http://localhost:4000/admin/province/units
# http://localhost:4000/cba/roads/snapshots
# http://orma-uat.drvn.gov.vn:4000/cba/roads/snapshots
# http://orma-uat.drvn.gov.vn:4000/cba/user_configs

POST http://localhost:4000/cba/roads/snapshots/take HTTP/1.1
content-type: application/json

{
    "name": "Jame Test",
    "province_id": 294,
    "num_records": 888,
    "valid_records": 420

} 