# Get all user configs
# http://localhost:4000/cba/user_configs/1

# http://localhost:4000/cba/user_configs/1/traffic_levels

# Create a new config
POST http://localhost:4000/cba/user_configs/1/update HTTP/1.1
content-type: application/json

{
    "name": "Jamie Test",
    "discount_rate": 3.9,
    "economic_factor": 1.2
}


# POST http://localhost:4000/cba/user_configs/create HTTP/1.1
# content-type: application/json

# {
#     "name": "Ha Ziang",
#     "discount_rate": 2.9,
#     "economic_factor": 0.7
# }

# GET http://localhost:4000/cba/user_configs/1/traffic_levels HTTP/1.1